// Generated by https://quicktype.io

export interface IOrders {
    _id:             ID;
    orderNumber:     string;
    clientId:        ID;
    shippingAddress: IngAddress;
    billingAddress:  IngAddress;
    products:        Product[];
    numberOfItems:   number;
    subtotal:        number;
    tax:             Tax;
    total:           number;
    paidAt:          string;
    transactionId:   string;
    orderStatus:     string;
    provider:        "paypal" | "stripe";
    discounts:       Discount[];
    shippingPrice:   number;
}

export interface ID {
    $oid: string;
}

export interface IngAddress {
    firstName: string;
    lastName:  string;
    address:   string;
    address2:  string;
    city:      string;
    estate:    string;
    country:   string;
    zip:       string;
    phone:     string;
    _id:       ID;
}


export interface Discount {
    code:       Code;
    quantity:   number;
    percentaje: number;
    _id:        ID;
}

export enum Code {
    Andres15 = "andres15",
    Andres25 = "andres25",
}

export interface Product {
    title:       string;
    variantName: string;
    slug:        string;
    image:       string;
    price:       number;
    quantity:    number;
    description: string;
    _id:         ID;
}

export interface Tax {
    percent: string;
    amount:  string;
    _id:     ID;
}
