// Generated by https://quicktype.io

export interface IOrders {
    _id:             ID;
    orderNumber:     string;
    clientId:        ID;
    shippingAddress: IngAddress;
    billingAddress:  IngAddress;
    products:        Product[];
    numberOfItems:   number;
    subtotal:        number;
    tax:             Tax;
    total:           number;
    paidAt:          string;
    transactionId:   string;
    orderStatus:     string;
    provider:        Provider;
    discounts:       Discount[];
    shippingPrice:   number;
}

export interface ID {
    $oid: string;
}

export interface IngAddress {
    firstName: string;
    lastName:  string;
    address:   string;
    address2:  string;
    city:      string;
    estate:    string;
    country:   Country;
    zip:       string;
    phone:     string;
    _id:       ID;
}

export enum Country {
    México = "méxico",
}

export interface Discount {
    code:       Code;
    quantity:   number;
    percentaje: number;
    _id:        ID;
}

export enum Code {
    Andres15 = "andres15",
    Andres25 = "andres25",
}

export interface Product {
    title:       Title;
    variantName: VariantName;
    slug:        Slug;
    image:       string;
    price:       number;
    quantity:    number;
    description: Description;
    _id:         ID;
}

export enum Description {
    CajaCon10Barras = "Caja con 10 barras",
    CajaCon18Barras = "Caja con 18 barras",
    The5Cajas90Piezas18PzPorCaja = "5 cajas-90 piezas-18pz por caja",
}

export enum Slug {
    ChocolateAmargo73Cacao = "chocolate_amargo_73-cacao",
    ChocolateAmargoPremium = "chocolate_amargo_premium",
    ChocolateBlancoArtesanal = "chocolate_blanco_artesanal",
    ChocolateDeLechePremium = "chocolate_de-leche_premium",
    DistribuidorPack = "distribuidor_pack",
}

export enum Title {
    ChocolateAmargo73Cacao = "chocolate amargo 73% cacao",
    ChocolateAmargoPremium = "chocolate amargo premium",
    ChocolateBlancoArtesanal = "chocolate blanco artesanal",
    ChocolateDeLechePremium = "chocolate de leche premium",
    DistribuidorPack = "distribuidor pack",
}

export enum VariantName {
    Empty = ".",
    The18G = "18g",
    The35G = "35g",
}

export enum Provider {
    Paypal = "paypal",
    Stripe = "stripe",
}

export interface Tax {
    percent: string;
    amount:  string;
    _id:     ID;
}
